# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Plex
    url: http://maynardserver.duckdns.org:32400
  - name: Home Assistant
    url: http://maynardserver.duckdns.org:8123
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: Overseer
    url: http://maynardserver.duckdns.org:5055

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /MaynardHome
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Welcome  
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/marksmaynard1/MaynardHome/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
